# Generated by Django 2.2.3 on 2019-07-04 15:27

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190704_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
