# Generated by Django 2.2.3 on 2019-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190705_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=str, upload_to='images/'),
            preserve_default=False,
        ),
    ]
